[package]
name = "image-filter"
version = "0.2.1"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
cliclack = "0.3.5"
console = "0.15.8"
ctrlc = "3.4.5"
image = "0.25.4"
tokio = { version = "1.41.0", features = ["rt", "rt-multi-thread"] }

[[bin]]
name = "imgf"
path = "src/main.rs"
