[package]
name = "image-filter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
cliclack = "0.3.5"
console = "0.15.8"
image = "0.25.4"
tokio = { version = "1.41.0", features = ["rt", "rt-multi-thread"] }
